### ISSUE TITLE
Segmentation Masks

### ISSUE THREAD

**Issue by waqar3411** [ualsg/global-streetscapes#2]
Hi, 
I have been looking at this dataset for some time. I managed to download some sample images containing trash cans. Now i want to download the segmentation masks for these images. As far i k now, your repository does not provide any information of getting the segmentation mask using either instances.csv or segmentation.csv.
I might be missing something. Can you help me Identify and download the segmentation masks which are predicted by your method for the images i want.
Thank you

**Comment by Junguin** [comment]
Hi @waqar3411, thanks for your interest in the dataset! we didn't include the segmentation masks because we had to save storage space, but only provide the pixel and instance counts.

**Comment by waqar3411** [comment]
So this dataset, can not be used for instance segmentation, but only for image classification based on the presence of the desired object? am i right?
